#!/bin/bash

if [ ! -f "vendor/bin/php-cs-fixer" ];
then
  echo "vendor/bin/php-cs-fixer not found!"
  exit 1
fi

while read -r file;
do
  if [[ $file = *.php ]];
  then
    docker exec -i ep.pv vendor/bin/php-cs-fixer fix "$file" --config=.php_cs -v  --using-cache=no --path-mode=intersection
    git add "$file"
  fi
done < <(git diff --cached --name-status --diff-filter=ACM | awk '{print $2}')

timestamp() {
    date +"%s"
}

if [ -e "assetVersion.txt" ];
then
    rm "assetVersion.txt"
fi

echo $(timestamp) >> "assetVersion.txt"

git add assetVersion.txt
